# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d1ca3ca34f3a91f94d384e38133493283e424fdcbfb4074c1410eed430120045feafb8baf61f18c2908152ee4843ec080d438cd09fa63a03ad9aebf2127684c

test:
  secret_key_base: 6b728cb0e61b0e0a5037c6525dde62aabfb56ba6db1665570b83415f671ff129232c523110b4de0410fd130ed5769d122566aeb59ab6aeea95e38db3f2079230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
